### ISSUE TITLE
Syntax Error: Unexpected &

### ISSUE THREAD

**Issue by bartosz-zawada** [appjudo/skim#45]
After updating, I found out that doing this:

    - class_name = 'ruby'
    .hello class=class_name Hello Ruby!

Would throw an Syntax Error: Unexpected &
class_name must not be static, it's a strange case that has to do with attribute merging.

I found that the commit '187084f' to be the culprit. The exact change that causes this is:

    +    html :AttributeMerger

I'm not actually sure what this lines does as I haven't dealt with Temple before, but commenting that line fixes the problem for me.

I fixed that in my fork, and also added two tests to verify it.
This is the fork: https://github.com/bartosz-zawada/skim

**Comment by gkopylov** [comment]
@bartosz-zawada "html :AttributeMerger" was added earlier and this was made for support this feature https://github.com/judofyr/temple/blob/master/lib/temple/html/attribute_merger.rb

For your case I think it would be better and cleaner to write this:
```
- class_name = 'ruby'
div class = "hello #{ class_name }" Hello Ruby!
```
So that case class is defined only in one place.

Btw, I think it would be better to create github organization("skim" for example) though because otherwise  there will many forks and nobody will support this in actual state.

**Comment by amenzhinsky** [comment]
I'm getting the same error using code like this:

```
button.btn class=('active' if @active)
```

I suppose it's not a feature :smile:

**Comment by gkopylov** [comment]
@amenzhinsky why not just to use this code:
```
button class = "btn #{ 'active' if @active }"
```

**Comment by gkopylov** [comment]
Using class name after dot and with ```class``` directive simultaneously is confusing. I think it would be better to use it either with dot or with ```class``` directive only.

**Comment by amenzhinsky** [comment]
@gkopylov I do understand in some cases it's confusing, but in examples like I posted above it would be nice to have. Maybe you're right :+1:

**Comment by alubbe** [comment]
It's unfortunate because
```
.staticClass class=@dynamicClassName
```
is valid slim. Why deviate?

**Comment by hgani** [comment]
I agree with @alubbe 

We should maintain compatibility with slim because the main reason people use this gem is that they want to use slim for JS templating.

**Comment by pavelkomiagin** [comment]
I agree with @bartosz-zawada that we shouldn't use "html :AttributeMerger". Could you make a pull request with it?

**Comment by ryanwood** [comment]
Any progress on merging @pavelkomiagin's PR?
