### ISSUE TITLE
Iterating and working with collections

### ISSUE THREAD

**Issue by Bassov** [appjudo/skim#51]
Hello,

I have a trouble with iterating over an array. I have an array of objects, that have other objects and i want to get this value in each element of array and past it in link. In ruby i will use this code:

```
- if @attachments
  - @attachments.each do
    a href="#{@attachments.file.url}" "#{@attachments.file_name}"
```

So how I can handle it in skim? I cant find the way.

**Comment by achempion** [comment]
Skim is not based on ruby, skim is based on coffee, so, just write you code in coffee instead of ruby :)

here is an example of what you need - https://github.com/appjudo/skim/blob/master/test/test_code_blocks.rb#L75
